
###
# replace with url to backend server below
@baseUrl= http://localhost:5002/api/geography 

###
get {{baseUrl}}/validateCity/MA/Fall%20River

###
get {{baseUrl}}/validatePostCode/02116

###
get {{baseUrl}}/cityArray/MA

###
get http://localhost:3000/proxy-api/geography/validateCity/MA/Boston














###
# create record
post {{baseUrl}}/api/create
Content-Type: application/json

{
 "name": "John Smith",
 "age": 34,
 "location": "New York City"
}